### ISSUE TITLE
vignette development

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.gee#12]
refer to tern.mmrm for examples

https://github.com/insightsengineering/tern.mmrm/tree/main/vignettes

branch off and merge back to `2_prototype`

**Comment by edelarua** [comment]
@shajoezhu I think this requires more technical knowledge of GEE models (and SAS) than our team has to make it as detailed as the equivalent `tern.mmrm` vignette. Is this issue better suited to the Stats Eng. team?

**Comment by shajoezhu** [comment]
Hi @edelarua , I think we can give a first go at this. :)
