### ISSUE TITLE
cran release 0.1.3

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.gee#39]
- [x] https://github.com/insightsengineering/tern.gee/issues/44
- [x]  Update README and NEWS.md
- [x]  create cran_releae_0.1.1_branch
- [x]  update DESCRIPTION
- [x] fix invalid URL to rtables GH pages
- [x] extend description text, current one is too short
- [x]  Submission to CRAN
- [x]  Address any CRAN feedback:
	- [x] Please write references in the description of the DESCRIPTION file in the form authors (year) `<doi:...>`, authors (year) `<https:...>` - So please add authors and (year) as well.
	- [x] The LICENSE file is only needed if you have additional restrictions to the license which you have not? In that case omit the file and its reference in the DESCRIPTION file.
    - [x] Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar) Missing Rd-tags:
        - [x] gee_methods.Rd: \value
        - [x] tabulate_gee.Rd: \value
    - [x] You write information messages to the console that cannot be easily suppressed.
			It is more R like to generate objects that can be used to extract the
			information a user is interested in, and then print() that object.
			Instead of cat() rather use message()/warning() or if(verbose)cat(..)
			(or maybe stop()) if you really have to write text to the console.
			(except for print, summary, interactive functions) -> 
         - [x] R/fit_gee.R
- [x]  Acceptance on CRAN
- [x]  tag v0.1.3
- [x]  merge cran_releae_0.1.1_branch

**Comment by danielinteractive** [comment]
Apologies, I needed to go up to 0.1.2 because of some minor issues with 0.1.1 that I detected myself...
