### ISSUE TITLE
[Feature Request]: Please rename lsmeans()

### ISSUE THREAD

**Issue by rvlenth** [insightsengineering/tern.gee#59]
### Feature description

I updated **emmeans** and it failed a CRAN check because the update includes an `rbind()` method for `summary_emm` objects, and that caused a conflict with the `rbind()` call in your `lsmeans()` function. I was able to devise a workaround, so that your package passes the checks.

But the real point is that this experience brought to light what I view as an unacceptable situation, and that is that **tern.gee** contains an `lsmeans()` function that is conflicts in several ways with a function of the exact same name in the **emmeans** package. `emmeans::lsmeans()` is an alternative way to call `emmeans::emmeans()`; in fact it just calls `emmeans()` and renames some of the estimates. `emmeans::lsmeans()` returns an `emmGrid` object. 

Meanwhile, `tern.gee::lsmeans()` actually calls `emmeans::emmeans()` to do the bulk of its work, then reshapes it in a few ways and returns a `data.frame`. Many users of **tern.gee** will have had experience with `emmeans()` and may in fact have it in their search path. So they are likely to have two extremely different `lsmeans()` functions that do similar things, but are completely incompatible with one another. 

The **emmeans** package is very well established and has a large user base. The package in fact used to be **lsmeans**, and that package just loads **emmeans** so that it still works the same way as shown in some textbooks and other resources. If your package didn't actually use **emmeans** to do its work, I might be more accommodating; but I think this creates a very confusing situation for users, and I also don't want to have to handle user questions where they are actually asking about your `lsmeans()` instead of mine.

Therefore, I am writing to request that you rename your `lsmeans()` to something else; perhaps something like `lsmtable()` because it produces a table of least-squares means results. I have no objection to your providing that functionality, my objection is only to the name of the function. Obviously, there will need to be a deprecation period.

By the way, I had to agree to the code of conduct and contributor guidelines in order to submit this report, but those materials are not available through the links provided. I hope that you find this request respectful and appropriate; it is intended that way.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by rvlenth** [comment]
Here's an illustration showing use of the two different functions on the same model:
```
> tern.gee::lsmeans(model)
  ARMCD  prop_est prop_est_se prop_lower_cl prop_upper_cl   n   or_est or_lower_cl
1   PBO 0.9005656  0.01982120     0.8544189     0.9332277 420       NA          NA
2   TRT 0.9469490  0.01347376     0.9134350     0.9679432 380 1.970852    1.031652
  or_upper_cl log_or_est log_or_lower_cl log_or_upper_cl conf_level
1          NA         NA              NA              NA       0.95
2    3.765083  0.6784657      0.03116157         1.32577       0.95

> emmeans::lsmeans(model, as.formula(paste("~", model$vars$arm)))
 ARMCD lsmean    SE  df asymp.LCL asymp.UCL
 PBO     2.28 0.240 Inf      1.81      2.75
 TRT     2.96 0.276 Inf      2.41      3.50

Results are averaged over the levels of: RACE 
Covariance estimate used: vbeta 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95

**Comment by shajoezhu** [comment]
dear @rvlenth , thanks for raising this. I was wondering if you could show us your sessioninfo for the package versions please. many thanks!

**Comment by rvlenth** [comment]
Per your request, here is a reprex of a different example, with session info added
``` r
library(tern.gee)
## Loading required package: tern
## Loading required package: rtables
## Loading required package: formatters
## 
## Attaching package: 'formatters'
## The following object is masked from 'package:base':
## 
##     %||%
## Loading required package: magrittr
## 
## Attaching package: 'rtables'
## The following object is masked from 'package:utils':
## 
##     str
## Registered S3 method overwritten by 'tern':
##   method   from 
##   tidy.glm broom

example(lsmeans)
## 
## lsmens> df <- fev_data
## 
## lsmens> df$AVAL <- rbinom(n = nrow(df), size = 1, prob = 0.5)
## 
## lsmens> fit <- fit_gee(vars = vars_gee(arm = "ARMCD"), data = df)
## Registered S3 methods overwritten by 'geeasy':
##   method       from   
##   drop1.geeglm MESS   
##   drop1.geem   MESS   
##   plot.geeglm  geepack
## 
## lsmens> lsmeans(fit)
##   ARMCD  prop_est prop_est_se prop_lower_cl prop_upper_cl   n   or_est
## 1   PBO 0.4958214  0.02195164     0.4529337     0.5387708 420       NA
## 2   TRT 0.5019064  0.02585491     0.4513851     0.5523889 380 1.024639
##   or_lower_cl or_upper_cl log_or_est log_or_lower_cl log_or_upper_cl conf_level
## 1          NA          NA         NA              NA              NA       0.95
## 2   0.7853918    1.336766 0.02434049      -0.2415725       0.2902535       0.95
## 
## lsmens> lsmeans(fit, conf_level = 0.90, weights = "equal")
##   ARMCD  prop_est prop_est_se prop_lower_cl prop_upper_cl   n   or_est
## 1   PBO 0.4958214  0.02195164     0.4529337     0.5387708 420       NA
## 2   TRT 0.5019064  0.02585491     0.4513851     0.5523889 380 1.024639
##   or_lower_cl or_upper_cl log_or_est log_or_lower_cl log_or_upper_cl conf_level
## 1          NA          NA         NA              NA              NA        0.9
## 2   0.8196968    1.280822 0.02434049      -0.1988207       0.2475017        0.9

emmeans::lsmeans(fit, as.formula(paste("~", fit$vars$arm)), 
                 weights = "prop", type = "resp")
##  ARMCD lsmean     SE  df asymp.LCL asymp.UCL
##  PBO    0.496 0.0220 Inf     0.453     0.539
##  TRT    0.502 0.0259 Inf     0.451     0.552
## 
## Covariance estimate used: vbeta 
## Confidence level used: 0.95 
## Intervals are back-transformed from the logit scale

sessionInfo()
## R version 4.4.0 (2024-04-24 ucrt)
## Platform: x86_64-w64-mingw32/x64
## Running under: Windows 11 x64 (build 22631)
## 
## Matrix products: default
## 
## 
## locale:
## [1] LC_COLLATE=English_United States.utf8 
## [2] LC_CTYPE=English_United States.utf8   
## [3] LC_MONETARY=English_United States.utf8
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.utf8    
## 
## time zone: America/Chicago
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] tern.gee_0.1.3.9006 tern_0.9.4          rtables_0.6.7      
## [4] magrittr_2.0.3      formatters_0.5.6   
## 
## loaded via a namespace (and not attached):
##  [1] gtable_0.3.5       xfun_0.43          ggplot2_3.5.1      lattice_0.22-6    
##  [5] vctrs_0.6.5        tools_4.4.0        Rdpack_2.6         generics_0.1.3    
##  [9] sandwich_3.1-0     tibble_3.2.1       fansi_1.0.6        pkgconfig_2.0.3   
## [13] R.oo_1.26.0        Matrix_1.7-0       checkmate_2.3.1    ggridges_0.5.6    
## [17] lifecycle_1.0.4    R.cache_0.16.0     geeasy_0.1.2       stringr_1.5.1     
## [21] compiler_4.4.0     munsell_0.5.1      codetools_0.2-20   htmltools_0.5.8.1 
## [25] yaml_2.3.8         nloptr_2.0.3       pillar_1.9.0       tidyr_1.3.1       
## [29] MASS_7.3-60.2      R.utils_2.12.3     boot_1.3-30        multcomp_1.4-25   
## [33] mosaicCore_0.9.4.0 nlme_3.1-164       styler_1.10.3      tidyselect_1.2.1  
## [37] digest_0.6.35      stringi_1.8.4      mvtnorm_1.2-4      dplyr_1.1.4       
## [41] purrr_1.0.2        forcats_1.0.0      geepack_1.3.10     splines_4.4.0     
## [45] labelled_2.13.0    fastmap_1.1.1      grid_4.4.0         colorspace_2.1-0  
## [49] cli_3.6.2          survival_3.5-8     utf8_1.2.4         geeM_0.10.1       
## [53] broom_1.0.5        TH.data_1.1-2      ggformula_0.12.0   clipr_0.8.0       
## [57] withr_3.0.0        scales_1.3.0       backports_1.4.1    estimability_1.5.1
## [61] rmarkdown_2.26     emmeans_1.10.2     lme4_1.1-35.3      hms_1.1.3         
## [65] zoo_1.8-12         R.methodsS3_1.8.2  coda_0.19-4.1      evaluate_0.23     
## [69] haven_2.5.4        knitr_1.46         rbibutils_2.2.16   rlang_1.1.3       
## [73] MESS_0.5.12        Rcpp_1.0.12        xtable_1.8-4       glue_1.7.0        
## [77] reprex_2.1.0       minqa_1.2.6        rstudioapi_0.16.0  R6_2.5.1          
## [81] fs_1.6.4
```

<sup>Created on 2024-05-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by rvlenth** [comment]
After sleeping on this, I decided that my request may be inappropriate. I do feel that this naming might create confusion among your users; but it is not my business to tell you what to do about it. So you may ignore my request. 

I do, however, hope you will merge the pull request (#60) that I submitted. This avoids having your `rbind()` call dispatched to an **emmeans** package method rather than the intended **base** method.

**Comment by shajoezhu** [comment]
close as #60 merged
