### ISSUE TITLE
[Bug]: Change in emmeans package causes an error in tern.gee

### ISSUE THREAD

**Issue by rvlenth** [insightsengineering/tern.gee#67]
### What happened?

The **emmeans** package supports both **glmgee** and **geeglm** objects, but it was inconsistent in that the latter used infinite d.f. while the former used finite d.f. I have a new update to **emmeans** that makes them consistent with one another and both now use the finite d.f. (See [emmeans issue 496](https://github.com/rvlenth/emmeans/issues/496).)This changes some column names in the summaries -- specifically, the confidence limits are now named `lower.CL` and `upper.CL` instead of `asymp.LCL` and `asymp.UCL`, as is expected in the third line in the code for `lsmeans.tern_gee_logistic()`. 

Because the d.f. change was a bug fix in **emmeans**, I don't want to revert the change, so I am requesting that you change **gee.tern** so it is compatible.

### Additional comment
You have an `lsmeans()` function that has the same name -- but is incompatible with -- a function of the same name in **emmeans**. This will confuse your users because they will get different results depending on which package is earlier in the search path:
```
> tern.gee::lsmeans(fev_fit, data = fev_data)
Error in `[.data.frame`(data.frame(stats::confint(prop_emm)), , c(object$vars$arm,  : 
  undefined columns selected
> # This is the current error message due to the issue reported here

> emmeans::lsmeans(fev_fit, data = fev_data)
Error in emmfcn(...) : argument "specs" is missing, with no default
> # Due to incompatibility between the two functions
```

### Relevant log output

```R
(No additional material needed)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by rvlenth** [comment]
OK, 1.10.4 is now on CRAN

**Comment by shajoezhu** [comment]
Thanks so much @rvlenth , I will prep for a CRAN release
